Feature/#26 매칭 관련 코드
4Ailen/backend pull request #34
Opened 2023-01-18 14:04 UTC by JeongeunChoi

## 🤨 Motivation

- Resolved #26

## 🔑 Key Changes 

- API doc 기반으로 매칭 컨트롤러 코드 추가
- 매칭 서비스 코드 추가
- 리포지토리 코드 추가

## 🙏 To Reviewers 

- jwt는 제외하고 매칭만 구현했습니다!
- db에 임의로 데이터 넣어서 포스트맨으로 실행하여 확인했습니다!
- 팀 매칭하는 로직은 우선 /matching/result 호출 시 실행되도록 해뒀는데 나중에 특정 날짜가 되면 실행되도록 해야할까요?

2023-01-19 18:31 UTC, coke98 requested changes
고생하셨습니다! 컨트롤러 부분에서 궁금한게 생겨서 먼저 리뷰 남겨요, 서비스 로직은 내일 한번 다시 확인해볼게요!

2023-01-19 18:31 UTC, coke98 commented on src/main/java/com/aliens/friendship/controller/MatchingController.java
> +    public Question getQuestion() {
메서드 반환값들에 "apiRes<  >"를 사용해보는건 어떨까요?!

2023-01-19 18:31 UTC, coke98 commented on src/main/java/com/aliens/friendship/controller/MatchingController.java
> +        return matchingService.getLanguages();
List형을 반환하면, language:[ ] 처럼 key value형태로 반환 못하지 않나용??

2023-01-19 18:31 UTC, coke98 commented on src/main/java/com/aliens/friendship/controller/MatchingController.java
> +    public JSONObject getStatus() throws ParseException {
반환값으로 json을 반환하고 싶은거라면, Map<String, Object> 반환형이나, Dto를 사용해보는건 어떨까요?  여기서 Dto를 활용하기에는 status값 하나밖에 없어서 그렇다 치더라도,  다른 메서드에서는 dto로 반환해도 좋을 것 같아요

2023-01-20 00:50 UTC, JeongeunChoi commented on src/main/java/com/aliens/friendship/controller/MatchingController.java
> +    public Question getQuestion() {
넵넵 수정했습니다!

2023-01-20 00:50 UTC, JeongeunChoi commented on src/main/java/com/aliens/friendship/controller/MatchingController.java
> +        return matchingService.getLanguages();
ㅎ... 그러네요! Map으로 수정했습니다! 감사합니다 :)

2023-01-20 00:51 UTC, JeongeunChoi commented on src/main/java/com/aliens/friendship/controller/MatchingController.java
> +    public JSONObject getStatus() throws ParseException {
약간 걸리는 부분이었는데 Map으로 작성하면 되겠네요! 감사합니다!!

2023-01-21 11:28 UTC, coke98 requested changes

2023-01-21 11:28 UTC, coke98 commented on src/main/java/com/aliens/friendship/service/MatchingService.java
> +        Map<Integer, String> languageMap = new HashMap<>();
[korea,0] 형식으로 반환한다면 < String, Object > 나 < String, Integer > 가 맞지 않나요?

2023-01-21 11:28 UTC, coke98 commented on src/main/java/com/aliens/friendship/service/MatchingService.java
> +            languageMap.put(language.getId(), language.getLanguageText());
language:[[korea,0],[~~,~~]] 형식으로 반환되는게 맞나요?? language라는 키 값이 안보이네요

2023-01-21 11:28 UTC, coke98 commented on src/main/java/com/aliens/friendship/service/MatchingService.java
> +        member.setIsApplied("apply");
요거 나중에 enum.String으로 관리하면 좋을 것 같아요. 나중에 멤버 클래스에 추가할게요.

2023-01-21 11:28 UTC, coke98 commented on src/main/java/com/aliens/friendship/service/MatchingService.java
> +                .groupId(-1)
groupId 초기 생성값을 -1로 하도록 MatchingParticipant 클래스에 @builder.default를 사용하보면 좋을 것 같아요. default값 관련해서도 엔티티 전부 수정하도록 이슈 파놓을게요

2023-01-21 11:28 UTC, coke98 commented on src/main/java/com/aliens/friendship/service/MatchingService.java
> +    void convertStatus() {
메서드 명 updateStatus(CRUD) 는 어떨까요?

2023-01-21 11:28 UTC, coke98 commented on src/main/java/com/aliens/friendship/service/MatchingService.java
> +    // 매칭 완료 후 member와 matching_participant status 변경
member도 변경되어야 하는 점이 있나요?

2023-01-21 11:28 UTC, coke98 commented on src/main/java/com/aliens/friendship/service/MatchingService.java
> +    static List<BlockingInfo> blockingInfos; // 사용자들의 차단 정보
static 변수를 사용하신 이유가 따로 있는지 궁금합니다!

2023-01-21 14:23 UTC, coke98 reviewed
고생하셨어요! 수정되는대로 머지할게요!

2023-01-21 14:23 UTC, coke98 commented on src/main/java/com/aliens/friendship/controller/MatchingController.java
> +    public ApiRes<Map<String, List<List<String>>>> getLanguages() {
꿀팁 한스푼 Map< String, Object >로 두시면 됩니다!

2023-01-21 14:23 UTC, coke98 commented on src/main/java/com/aliens/friendship/service/MatchingService.java
> +    public Map<String, List<List<String>>> getLanguages() {
마찬가지!

2023-01-21 14:23 UTC, coke98 commented on src/main/java/com/aliens/friendship/service/MatchingService.java
> +        List<List<String>> language_list = new ArrayList<>();
카멜케이스!

2023-01-21 14:23 UTC, coke98 commented on src/main/java/com/aliens/friendship/service/MatchingService.java
> +        List<List<String>> language_list = new ArrayList<>();
아마 < Object > 쓰셔도 될거에요

2023-01-21 14:23 UTC, coke98 commented on src/main/java/com/aliens/friendship/service/MatchingService.java
> +            List<String> lg = new ArrayList<>();
리뷰어들을 위해서도, 유지보수를 위해서도 변수병에 줄임을 최대한 사용하지 않았으면 하는 바람입니다!

2023-01-21 14:23 UTC, coke98 commented on src/main/java/com/aliens/friendship/service/MatchingService.java
> +        return map;
개인적으로는 result같은 변수를 써서 자료형보다는 의미를 전달하면 좋을 것 같아요!

2023-01-21 15:01 UTC, JeongeunChoi commented on src/main/java/com/aliens/friendship/controller/MatchingController.java
> +    public ApiRes<Map<String, List<List<String>>>> getLanguages() {
오 진짜 꿀팁이네요! 감사합니다 :)

2023-01-21 15:01 UTC, JeongeunChoi commented on src/main/java/com/aliens/friendship/service/MatchingService.java
> +        List<List<String>> language_list = new ArrayList<>();
네넵 감사합니다 :)

2023-01-21 15:02 UTC, JeongeunChoi commented on src/main/java/com/aliens/friendship/service/MatchingService.java
> +            List<String> lg = new ArrayList<>();
네넵 변수명 수정했습니다!

2023-01-21 15:03 UTC, JeongeunChoi commented on src/main/java/com/aliens/friendship/service/MatchingService.java
> +        return map;
아 그렇겠네요. result로 수정했습니다!!

2023-01-22 05:49 UTC, merged